# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  eepyxr = {
    pname = "eepyxr";
    version = "b826495d60b297d4a7a38c3c10203c919209fc3d";
    src = fetchgit {
      url = "https://github.com/Beyley/eepyxr.git";
      rev = "b826495d60b297d4a7a38c3c10203c919209fc3d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-eDGIE/Mbc+52qAqjU+N5yrR23BO7PXLJTsZFG66qoqE=";
    };
    date = "2025-03-09";
  };
  envision-unwrapped = {
    pname = "envision-unwrapped";
    version = "32b222cd9e2749cfdecb216189f954c719e3f66e";
    src = fetchgit {
      url = "https://gitlab.com/gabmus/envision.git";
      rev = "32b222cd9e2749cfdecb216189f954c719e3f66e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-fEEbcfszPUkevu39dIdx2N9o4bJHjaEQy+LGsTQXJoA=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./envision-unwrapped-32b222cd9e2749cfdecb216189f954c719e3f66e/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2025-08-19";
  };
  index_camera_passthrough = {
    pname = "index_camera_passthrough";
    version = "0d3ec30c5cd74e4a3df93d704ecf4a25136afd73";
    src = fetchgit {
      url = "https://github.com/yshui/index_camera_passthrough.git";
      rev = "0d3ec30c5cd74e4a3df93d704ecf4a25136afd73";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-jldpVWnpWEA3bi3lzmG94uCaoZuL+xhaEAtFiZrSGc4=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./index_camera_passthrough-0d3ec30c5cd74e4a3df93d704ecf4a25136afd73/Cargo.lock;
      outputHashes = {
        "vulkano-0.34.0" = "sha256-co2+rDJ1jOee36x9FcLX2Pze9ZItBYHq9/pEq0NhcpY=";
      };
    };
    date = "2024-07-25";
  };
  monado = {
    pname = "monado";
    version = "08ec9009bfef58fb6b6e1965b0c4784d34cf6699";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/monado/monado.git";
      rev = "08ec9009bfef58fb6b6e1965b0c4784d34cf6699";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/grHHrf+m0To07e6pz+K5qAN9LLIDM2xNG6sLoS2wbg=";
    };
    date = "2025-08-25";
  };
  opencomposite = {
    pname = "opencomposite";
    version = "cff07db75c4823afe93ed7027b03d5f7bc86f164";
    src = fetchgit {
      url = "https://gitlab.com/znixian/OpenOVR.git";
      rev = "cff07db75c4823afe93ed7027b03d5f7bc86f164";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-nie+8g/P9aZYimuLJxrzN+frfA772VyPDf2ThyguqBM=";
    };
    date = "2025-07-21";
  };
  vapor = {
    pname = "vapor";
    version = "6d273cb6c7db0847daee1276be20886e6ff515ae";
    src = fetchgit {
      url = "https://github.com/micheal65536/VapoR.git";
      rev = "6d273cb6c7db0847daee1276be20886e6ff515ae";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Ul7TBMyWnvsEIdaA0gEKiB5SNoiOSrcF937lkuZPUEg=";
    };
    date = "2025-05-27";
  };
  wayvr-dashboard = {
    pname = "wayvr-dashboard";
    version = "adf31946c88824d60dc51dc79a52e891b3efd7e7";
    src = fetchgit {
      url = "https://github.com/olekolek1000/wayvr-dashboard";
      rev = "adf31946c88824d60dc51dc79a52e891b3efd7e7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+WEwTg9Z5p1TNoqUdh8Nke0KHa6k0AlA/myrYiF3rOU=";
    };
    cargoLock."src-tauri/Cargo.lock" = {
      lockFile = ./wayvr-dashboard-adf31946c88824d60dc51dc79a52e891b3efd7e7/src-tauri/Cargo.lock;
      outputHashes = {
        "keyvalues-parser-0.2.0" = "sha256-LT+WHhan/USzW0EOiuIBPG5j1r9qL4n7Z7ESDxO1xQQ=";
        "libmonado-1.3.1" = "sha256-HYYfpYhyo5VmbUdwMTJuAR+2dnMITIGZIPGX9Qsnc/g=";
        "wayvr_ipc-0.1.0" = "sha256-ieQaY08Ogl/F3t/p825LBp1lAO3SWH1F8206IPXEgTc=";
      };
    };
    date = "2025-08-10";
  };
  wivrn = {
    pname = "wivrn";
    version = "8f8e583eb67f9e381fb90b6a23a0a20056ce13a9";
    src = fetchFromGitHub {
      owner = "WiVRn";
      repo = "WiVRn";
      rev = "8f8e583eb67f9e381fb90b6a23a0a20056ce13a9";
      fetchSubmodules = false;
      sha256 = "sha256-vubg6e3E/JlQvYmFUiDTvMpqIfOh3CEob1Nadsrt77E=";
    };
    date = "2025-08-24";
  };
  wivrn-monado = {
    pname = "wivrn-monado";
    version = "5c137fe28b232fe460f9b03defa7749adc32ee48";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/monado/monado.git";
      rev = "5c137fe28b232fe460f9b03defa7749adc32ee48";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4P/ejRAitrYn8hXZPaDOcx27utfm+aVLjtqL6JxZYAg=";
    };
  };
  wlx-overlay-s = {
    pname = "wlx-overlay-s";
    version = "fbd518952127299dddea91122e0dcb53a0218568";
    src = fetchgit {
      url = "https://github.com/galister/wlx-overlay-s.git";
      rev = "fbd518952127299dddea91122e0dcb53a0218568";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-yT18j0v8MtpXwK4REIwgGDY5HNvxtMY2tqRGE/zF64w=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./wlx-overlay-s-fbd518952127299dddea91122e0dcb53a0218568/Cargo.lock;
      outputHashes = {
        "ovr_overlay-0.0.0" = "sha256-NHzESKsghqI98pkQxEmcNkQ9lTfBsqR9/25msbryi6E=";
        "openxr-0.19.0" = "sha256-mljVBbQTq/k7zd/WcE1Sd3gibaJiZ+t7td964clWHd8=";
        "wlx-capture-0.5.4" = "sha256-M8yOxmD8rseiYR6FJnoToHeKLkdgJNqnE6STppDi+cI=";
        "libspa-0.8.0" = "sha256-Gub2F/Gwia8DjFqUsM8e4Yr2ff92AwrWrszsws3X3sM=";
        "wayvr_ipc-0.1.0" = "sha256-ieQaY08Ogl/F3t/p825LBp1lAO3SWH1F8206IPXEgTc=";
      };
    };
    date = "2025-08-13";
  };
  xrizer = {
    pname = "xrizer";
    version = "bfaf59725c0f56e24f7b78b4dd6ac09f5859eafc";
    src = fetchgit {
      url = "https://github.com/Supreeeme/xrizer.git";
      rev = "bfaf59725c0f56e24f7b78b4dd6ac09f5859eafc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Js0wRa7+piI9Hm2gtWoTpixualA4By0M499PfIZ/+BA=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./xrizer-bfaf59725c0f56e24f7b78b4dd6ac09f5859eafc/Cargo.lock;
      outputHashes = {
        "openxr-0.19.0" = "sha256-mljVBbQTq/k7zd/WcE1Sd3gibaJiZ+t7td964clWHd8=";
      };
    };
    date = "2025-08-23";
  };
}
