# SPDX-FileCopyrightText: 2025 Sapphire <imsapphire0@gmail.com>
#
# SPDX-License-Identifier: MIT

# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAAokTgCCkRqtrvPINtODP3xgOG7h7kb-_7bFR4X3";
    path = fetchgit {
      url = "https://github.com/nothings/stb";
      rev = "5c205738c191bcb0abc65c4febfa9bd25ff35234";
      hash = "sha256-JeVkoaGZnxSE3EAIwImz/ArPcOee2++5Q8c3mwfLCr0=";
    };
  }
  {
    name = "N-V-__8AAC7GCAOYyx5ViWPip8IR15Gy3Zi0YCq5IedZYsQv";
    path = fetchgit {
      url = "https://github.com/libsdl-org/SDL";
      rev = "57f3d2ea0aada9131c109aaa0dfda41839997ebf";
      hash = "sha256-tLX3uY18hWMLzkeAMcvEc0BLZ1M4vgp4FIOmnvh1yIc=";
    };
  }
  {
    name = "known_folders-0.0.0-Fy-PJv3LAAABBRVoZWVrKZdyLoUfl5VRY5fqRRRdnF5L";
    path = fetchgit {
      url = "https://github.com/ziglibs/known-folders";
      rev = "83d39161eac2ed6f37ad3cb4d9dd518696ce90bb";
      hash = "sha256-faXaYD+0oe6M9iB4m46O6djWxXuuluNJeJdpIXNj8DM=";
    };
  }
]
