# SPDX-FileCopyrightText: 2025 Sapphire <imsapphire0@gmail.com>
#
# SPDX-License-Identifier: MIT

# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAAokTgCCkRqtrvPINtODP3xgOG7h7kb-_7bFR4X3";
    path = fetchgit {
      url = "https://github.com/nothings/stb";
      rev = "5c205738c191bcb0abc65c4febfa9bd25ff35234";
      hash = "sha256-JeVkoaGZnxSE3EAIwImz/ArPcOee2++5Q8c3mwfLCr0=";
    };
  }
  {
    name = "N-V-__8AAF1kjwP0nRUoy3Iy9y2SqguzbgsOIB-oL10oVITZ";
    path = fetchgit {
      url = "https://github.com/Beyley/SDL";
      rev = "d64e41f95ea641a32da18e526d57013966a96b41";
      hash = "sha256-rGpfU20sXz82utt1DXy+Mld+JJ65tdiip8tpKAndlrI=";
    };
  }
  {
    name = "known_folders-0.0.0-Fy-PJtLDAADGDOwYwMkVydMSTp_aN-nfjCZw6qPQ2ECL";
    path = fetchgit {
      url = "https://github.com/ziglibs/known-folders";
      rev = "aa24df42183ad415d10bc0a33e6238c437fc0f59";
      hash = "sha256-YiJ2lfG1xsGFMO6flk/BMhCqJ3kB3MnOX5fnfDEcmMY=";
    };
  }
]
